### ISSUE TITLE
PlatformException(unknown, null, null, null)

### ISSUE THREAD

**Issue by Caqil** [mysteriumnetwork/wireguard_dart#35]
flutter: initialize success
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(unknown, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
<asynchronous suspension>

**Comment by talkbiz** [comment]
@Caqil How did you resolved this?
