### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by Typical-User0** [mysteriumnetwork/wireguard_dart#9]
Hello, thank you for this project, I really need support for wireguard on multiple platforms with dart. I'm trying to launch your example project and get the following errors (both on linux and android): 

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method connect on channel wireguard_dart)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      MethodChannelWireguardDart.connect (package:wireguard_dart/wireguard_dart_method_channel.dart:24:5)
                                                                                                    <asynchronous suspension>`

`ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method generateKeyPair on channel wireguard_dart)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      MethodChannelWireguardDart.generateKeyPair (package:wireguard_dart/wireguard_dart_method_channel.dart:14:37)
                                                                                                    <asynchronous suspension>`

Can you help me? Please

**Comment by tadaskay** [comment]
Hey, it's not yet implemented for linux and android as mentioned in https://github.com/mysteriumnetwork/wireguard_dart/blob/master/README.md
